### ISSUE TITLE
combine legends for forest change 

### ISSUE THREAD

**Issue by dcarver1** [GeospatialCentroid/kenyaAfforestation#12]
On the Climate and management effects on forests tab map. Make a single legend for both the forest cover layers. 
This probably should be a togglable layer like the  Temperature/Precipitation Legend on map1. So it is turned on and off independently of the layers. **I couldn't get to to turn on and off with both layers. 
Values will range from 0-100 for both objects.

**Comment by dcarver1** [comment]
I've got the structure set up. Not sure about the wording/title. 
There are some assumption required on the user part to connect the legend to the historic and baseline datasets. 

-- note: max value is only 80 on legend. IF there is higher values then this then it would be good to show that.

**Comment by ccmothes** [comment]
Implementing leaflet proxy allowed me to find a better solution for this. Now there is an if() statement within its own proxy that identifies if at least one of the shared layers are added to the map, it will add the legend (and remove it if neither are selected). I implemented this for both map1 and map2
