### ISSUE TITLE
click reactivity on map element 2 

### ISSUE THREAD

**Issue by dcarver1** [GeospatialCentroid/kenyaAfforestation#14]
Currently selecting the Map provides the user no information. There are few thinks that I think could be added 

1. display historic, baseline, and project forest cover values (similar to map 1 with temp/prec) 
2. Have some hover over functionality or click to identify the county 

Probably more and better ideas out there.

**Comment by ccmothes** [comment]
I implemented reactivity to show the baseline forest cover and percent change. I thought these seemed like the most useful 2 numbers to compare, but open to adding other reactivity on map click.

**Comment by dcarver1** [comment]
We'll try to get some direct feedback from partners on this.

**Comment by dcarver1** [comment]
no direct feedback on this at this time. Expecting that it is acceptable as conveyed. Will close if no new changes come in the new few weeks.
