### ISSUE TITLE
slow load times 

### ISSUE THREAD

**Issue by dcarver1** [GeospatialCentroid/kenyaAfforestation#20]
Based on the discussion [here](https://community.rstudio.com/t/improving-shiny-app-loading-speed/5126/11)

1. Test variability between load time on shinyapp.io and locally 
2. Utilize the profvis library to evaluate where time is being spent 
3. evaluate implementing [shiny::req](https://shiny.rstudio.com/reference/shiny/latest/req.html)  -- for example test for the specific emissions category / tab before loading the map for those features. *not sure if we store that information as input$ feature or not.

**Comment by dcarver1** [comment]
the ignoreInit parameter of the observerEvent() might be a good options for reducing the amount of map computation needed at initialization 
https://shiny.rstudio.com/reference/shiny/1.7.4/observeevent

**Comment by ccmothes** [comment]
This was mostly due to leaflet re-projecting all rasters to its native crs (3857), so converted rasters to that CRS in the processing step
