### ISSUE TITLE
webpage selection options 

### ISSUE THREAD

**Issue by dcarver1** [GeospatialCentroid/kenyaAfforestation#26]
Consider 

*about* 
-- adding an about page that is describing the project, project partners, 

*modeling process* 
-- short summary 
-- summary of the modeling process and how it was validated 
-- external links (code base, input data) 
-- might be a organized by tab set or maybe a outline and single document 

Flexibility here.

**Comment by dcarver1** [comment]
added some of the basic structure the noGraze branch

**Comment by ccmothes** [comment]
These are both fully fleshed out in the #41 PR
