### ISSUE TITLE
build out the report download functionality 

### ISSUE THREAD

**Issue by dcarver1** [GeospatialCentroid/kenyaAfforestation#31]
Specifics of the reporting structure 
- select county 
- generate table of results 
- possible a map. 

Keep it simple for the first go at this. We really want to showcase the functionality and options that could be to show in the downloadable report. The specific needs will likely be informed by the in person interactions at the event.

**Comment by dcarver1** [comment]
carbon branch currently has the bare bone functionality baked in. 

To impliment 
- testing on shinyapps IO ; documentation reference some sensitive to this process when moved from local to server
- Enable pdf download 
- enable parameters to pass through reactive items 
- reformat existing reactive plots/charts as functions to allow them to be call within the report generation. 
-

**Comment by ccmothes** [comment]
This was completed with PR #35 . Still making minor edits to the report content.
