### ISSUE TITLE
develop some basic models to test understanding of the workflow

### ISSUE THREAD

**Issue by GeospatialCentroid** [GeospatialCentroid/kenyaAfforestation#4]
A little off base but starting to describe the system 
https://community.rstudio.com/t/shiny-app-composed-of-many-many-pages/7698/6
 - functional example provided : https://github.com/bborgesr/employee-dir

**Comment by dcarver1** [comment]
Visualized the functional needs of the current application here 

https://coggle.it/diagram/Yrivp2qIBdEcRy7R/t/kenya-afforestation
